version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    command: bash -c "php artisan serve --host=0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ="Asia/Tokyo"
    depends_on:
      - db
  app_testing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_testing
    command: bash -c "php artisan serve --host=0.0.0.0"
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql_test
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_memo_app_test
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ="Asia/Tokyo"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mydb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
